const Sequelize = require('sequelize');
const User = require('./test/user');
const Comment = require('./test/comment');
const Sensor = require('./sensor/sensor');
const NiModule = require('./sensor/niModule');
const VoltageChannel = require('./sensor/voltageChannel');
const CurrentChannel = require('./sensor/currentChannel');
const MicrophoneChannel = require('./sensor/microphoneChannel');
const AccelerometerChannel = require('./sensor/accelerometerChannel');
const ThermocoupleChannel = require('./sensor/thermocoupleChannel');
const SensorType = require('./sensor/sensorType');
const Users = require('./users');
const Role  = require('./role');
const Industrial = require('./industrial');
const Company = require('./company');
const CompanyFacilityMapper = require('./companyFacilityMapper');
const Task = require('./task');
const TaskWidget = require('./taskWidget');
const Facility = require('./facility');
const FacilityAttachments = require('./facilityAttachments');
const Mold = require('./mold');

const env = process.env.NODE_ENV || 'development';
const config = require('../config/config')[env];
const db = {};

const sequelize = new Sequelize(config.database, config.username, config.password, config);

db.sequelize = sequelize;

db.User = User;
db.Comment = Comment;
db.Sensor = Sensor;
db.NiModule = NiModule;
db.VoltageChannel = VoltageChannel;
db.CurrentChannel = CurrentChannel;
db.MicrophoneChannel = MicrophoneChannel;
db.AccelerometerChannel = AccelerometerChannel;
db.ThermocoupleChannel = ThermocoupleChannel;
db.SensorType = SensorType;
db.Users = Users;
db.Role = Role;
db.Industrial = Industrial;
db.Company = Company;
db.CompanyFacilityMapper = CompanyFacilityMapper;
db.Task = Task;
db.TaskWidget = TaskWidget;
db.Facility = Facility;
db.FacilityAttachments = FacilityAttachments;
db.Mold = Mold;

User.init(sequelize);
Comment.init(sequelize);
Sensor.init(sequelize);
NiModule.init(sequelize);
VoltageChannel.init(sequelize);
CurrentChannel.init(sequelize);
MicrophoneChannel.init(sequelize);
AccelerometerChannel.init(sequelize);
ThermocoupleChannel.init(sequelize);
SensorType.init(sequelize);
Users.init(sequelize);
Role.init(sequelize);
Industrial.init(sequelize);
Company.init(sequelize);
CompanyFacilityMapper.init(sequelize);
Task.init(sequelize);
TaskWidget.init(sequelize);
Facility.init(sequelize);
FacilityAttachments.init(sequelize);
Mold.init(sequelize);

User.associate(db);
Comment.associate(db);
Sensor.associate(db);
NiModule.associate(db);
VoltageChannel.associate(db);
CurrentChannel.associate(db);
MicrophoneChannel.associate(db);
AccelerometerChannel.associate(db);
ThermocoupleChannel.associate(db);
SensorType.associate(db);
Users.associate(db);
Role.associate(db);
Industrial.associate(db);
Company.associate(db);
CompanyFacilityMapper.associate(db);
Task.associate(db);
TaskWidget.associate(db);
Facility.associate(db);
FacilityAttachments.associate(db);
Mold.associate(db);

module.exports = db;